name: idhar_udhar
description: "Idhar Udhar Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  pin_code_fields: ^7.4.0
  intl: ^0.20.2
  google_maps_flutter: ^2.5.0
  sliding_up_panel: ^2.0.0
  flutter_animate: ^4.2.0
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  url_launcher: ^6.3.1
  android_intent_plus: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/payment/
    - assets/images/profile/
    - assets/images/home/
    - assets/images/ride/
    - assets/images/delivery/
    - assets/images/icons/
    - assets/images/avtars/
    - assets/images/
    - assets/animation/
    - assets/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: lexend
      fonts:
        - asset: assets/fonts/Lexend.ttf
